### ISSUE TITLE
AttributeError: module 'stir' has no attribute 'ImagingModality'

### ISSUE THREAD

**Issue by HyperionCore** [UCL/STIR#1401]
when I run the construct_projdata_demo.py, there is the error.
AttributeError: module 'stir' has no attribute 'ImagingModality'

**Comment by KrisThielemans** [comment]
Which STIR version is this? It should work in 6.0.0. 

Unfortunately, we have currently no way of finding the version out from Python.

**Comment by HyperionCore** [comment]
@KrisThielemans, yes, it is 6.0.0. I use this command to install: Conda install Conda-forge::stir, is it default version 6.0.0?

https://anaconda.org/conda-forge/stir

**Comment by KrisThielemans** [comment]
You need to use `conda list -n yourenvname stir` to check. If you use `conda install` in an existing environment (even the base one), conda will try to match versions of all dependencies, and select one accordingly. You never know what it's going to come up with really. If this is your problem, nest to use `conda create` as per the STIR wiki.
