### ISSUE TITLE
Unable to build STIR 4.0.1 with OpenMPI 

### ISSUE THREAD

**Issue by mastergari** [UCL/STIR#523]
STIR 4.0.1 fails to build with OpenMPI enabled on Ubuntu 18.04 (tested with OpenMPI 3.1.2 and 4.0.3). When building with OpenMPI 4.0.3 in the path, all paths appear correct in CMakeCache.txt (attached) but cmake states "found version 3.1". Build fails at 26% calling make -j24 or at 19% calling make with the first error message stating (see cmake_make-j24_MPI.txt and cmake_make_MPI.txt):
error: ‘using element_type = class stir::BackProjectorByBin {aka class stir::BackProjectorByBin}’ has no member named ‘set_output’; did you mean ‘get_output’?
     proj_pair_sptr->get_back_projector_sptr()->set_output(this->output_target_sptr);

Similar warning messages are produced when STIR is built with or without OpenMPI although building without OpenMPI is successful. The complete terminal output for the successful build without OpenMPI is attached in cmake_make_makeTest_makeInstall_noMPI.txt which includes output from cmake, make, make test, and make install. 

[cmake_make_makeTest_makeInstall_noMPI.txt](https://github.com/UCL/STIR/files/4565536/cmake_make_makeTest_makeInstall_noMPI.txt)
[cmake_make_MPI.txt](https://github.com/UCL/STIR/files/4565537/cmake_make_MPI.txt)
[cmake_make-j24_MPI.txt](https://github.com/UCL/STIR/files/4565538/cmake_make-j24_MPI.txt)
[CMakeCache.txt](https://github.com/UCL/STIR/files/4565539/CMakeCache.txt)
