### ISSUE TITLE
ECAT7 support broken (compilation errors)

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#578]
```
./src/STIR/src/IO/stir_ecat7.cxx:1383:45: error: there are no arguments to find_segment_sequence_in_stream that depend on a template parameter
```
bug introduced in #352 when renaming the function

**Comment by KrisThielemans** [comment]
Also
```
In file included from /slms/inm/research/tools/src/STIR/src/listmode_buildblock/CListModeDataECAT.cxx:28:0:
/slms/inm/research/tools/src/STIR/src/include/stir/listmode/CListRecordECAT966.h:169:1: error: expected class-name before  {  token
 {
```
bug introduced in https://github.com/UCL/STIR/pull/445.
