### ISSUE TITLE
building error with ITK version 5.0.1 related to ITKOutputFileFormat.cxx file

### ISSUE THREAD

**Issue by melkatib1** [UCL/STIR#489]
During the building procedure after configuring STIR with ITK capability using cmake-gui, the following error can occur :

''/home/mahmoud/software/STIRsoft/STIR/src/IO/ITKOutputFileFormat.cxx:157:21: error: ‘IteratorType {aka class itk::ImageRegionIterator<itk::Image<float, 3> >}’ has no member named ‘Begin’
       for ( it = it.Begin(); !it.IsAtEnd(); ++it, ++stir_iter  ){'' 

and it can be solved by modifying: '' for ( it = it.Begin(); !it.IsAtEnd(); ++it, ++stir_iter  ){'' in ''ItkOutputFileFormat.cxx''  by  '' for ( it.GoToBegin(); !it.IsAtEnd(); ++it, ++stir_iter  ){''

and building goes noemally to 100%.

**Comment by KrisThielemans** [comment]
@melkatib1, any news on this? I've recently enabled STIR's conda build to work with ITK 5.0 and didn't have this problem. Still I see no reason why not to put it in (unless it'd break older ITK versions, but I don't think so). Would be good to get this done then.

**Comment by melkatib1** [comment]
Hi dear Prof Kris,

Did you try it with version 3 ? Because its the version i installed,

Kind regards.


Le mer. 15 avr. 2020 à 17:51, Kris Thielemans <notifications@github.com> a
écrit :

**Comment by melkatib1** [comment]
I mean STIR version 3 😊

Le ven. 17 avr. 2020 à 12:18, Mohamed Mohamed <melkatib1@gmail.com> a
écrit :

**Comment by KrisThielemans** [comment]
Alright, this was already fixed on https://github.com/UCL/STIR/pull/257 2 years ago. Apologies that the official STIR release is so out-of-date.

I'd recommend using STIR_4.0.0alpha though.
