### PR TITLE
fix ECAT7 compilation problems due to renaming

### LINKED ISSUE #578: ECAT7 support broken (compilation errors)
```
./src/STIR/src/IO/stir_ecat7.cxx:1383:45: error: there are no arguments to find_segment_sequence_in_stream that depend on a template parameter
```
bug introduced in #352 when renaming the function

### PR DESCRIPTION
**Pull request by KrisThielemans**
Fixes #578

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Tested a tiny bit on Linux with `run_ecat_tests.sh`
