### ISSUE TITLE
#470 broke backwards compatibility too much

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#479]
Since merging #470, SIRF (and everyone else using STIR) will now get errors like https://travis-ci.org/github/CCPPETMR/SIRF/jobs/669274690#L22194
```
/home/travis/build/CCPPETMR/SIRF/src/xSTIR/cSTIR/include/sirf/STIR/stir_data_containers.h:85:24: error: no matching function for call to stir::ProjDataInterfile::ProjDataInterfile(std::shared_ptr<stir::ExamInfo>, std::shared_ptr<const stir::ProjDataInfo>, const string&, std::_Ios_Openmode)
```
caused by `get_proj_data_info_sptr` return now a `shared_ptr<const ProjDataInfo>`.

I suggest to add a constructor for `ProjDataInterfile`, `ProjDataInMemory` (and how many others?) that accepts this. They presumably will have to create their own clone. We could keep the original version as well, as this will allow people to pass a `shared_ptr<ProjDataInfo>`  and save the extra clone. (This constructor is a bit unsafe, but we do preserve the extra safety introduced by #470).

**Comment by KrisThielemans** [comment]
Doing a search on the use of `shared_ptr<ProjDataInfo>` in our `.*.h` files throws up about 90 places where this should be changed... Creating "double" constructors/`set_up*` functions etc is far too much work and would lead to far too much code duplication.

Seems it would be best to stick to using `shared_ptr<const ProjDataInfo>` in most places, indeed even in the class members. That would be better in any case (no scope for an object to sneakily modify a pointer that then would affect everybody else).

However, I have no idea if doing this wholesale (i.e. not keeping any `shared_ptr<ProjDataInfo>`  members/arguments at all), will be a ton of work, and/or will break too many things. In some sense, if we need to make changes in STIR code that uses the classes, then we know we will have trouble in SIRF/other places as well.

**Comment by rijobro** [comment]
Would you prefer to revert https://github.com/UCL/STIR/pull/470 until we sort this out?

**Comment by KrisThielemans** [comment]
depends a bit how long we're going to take with the suggested approach here. Would you be able to try something this morning? Possibly adding `const` in more places in the class interfaces (only) might not be too hard

**Comment by rijobro** [comment]
> Seems it would be best to stick to using shared_ptr<const ProjDataInfo> in most places, indeed even in the class members.

I agree with this. Can you think of any cases where the `ProjDataInfo` **shouldn't** be `const`?

**Comment by KrisThielemans** [comment]
Probably not, but I guess we'd find by trying it... I can't see any trouble in things like `Sinogram`, `LmToProjData` etc. Maybe it needs to be in `ProjData` itself, but I can't see why at the moment. 

Again, I'm hoping the only changes needed would be
- replace members to use `shared_ptr<const>`
- replace methods to use `shared_ptr<const>` (not sure if we need a `shared_ptr<const>&` or not)

**Comment by KrisThielemans** [comment]
This has been fixed.
