### ISSUE TITLE
MacOS brew ITK compilation error

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#654]
Related to #531, but possibly seperate

STIR ITK (via HomeBrew) install issue. Setting a clean directory to build in allows for cmake configeration and generation (work around for #531's issue). However, the make fails on:
```
[  8%] Building CXX object src/IO/CMakeFiles/IO.dir/ITKImageInputFileFormat.cxx.o
/Users/roberttwyman/bin/STIR/STIR/src/IO/ITKImageInputFileFormat.cxx:513:69: error: no member named 'VECTOR' in 'itk::ImageIOBase'
      if (reader->GetImageIO()->GetPixelType() != itk::ImageIOBase::VECTOR) {
                                                  ~~~~~~~~~~~~~~~~~~^
1 error generated.
make[2]: *** [src/IO/CMakeFiles/IO.dir/ITKImageInputFileFormat.cxx.o] Error 1
make[1]: *** [src/IO/CMakeFiles/IO.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by rijobro** [comment]
Brew ITK is now v5 (see [here](https://formulae.brew.sh/formula/itk)), and I think STIR normally requires v4. I wonder if that could be causing you problems.

**Comment by robbietuk** [comment]
@rijobro Ahh thank you. I installed ITK v4.13 manually allowing for STIR with ITK installation. Brew does not seem to allow ITK v4 to be installed.

**Comment by KrisThielemans** [comment]
Actually, we should keep up with ITK. I'm sure it worked fine with ITK 5.0, so I guess it's something recently introduced.

Having a look at `itk::ImageBaseIO`, this seems to be caused by an update that made it in ITK 5.1
https://github.com/InsightSoftwareConsortium/ITK/commit/0dd31a62f851a0ae95ef4c6d6c85e531a4ebca59. Code [before that](https://github.com/InsightSoftwareConsortium/ITK/blob/3fe9f0e7d1c09896f04a8f063d14a0525007a509/Modules/IO/ImageBase/include/itkImageIOBase.h#L114) used an ordinary `enum`, while since then there's some strongly-typed `enum` stuff. However, from [here](https://github.com/InsightSoftwareConsortium/ITK/blob/ddbc1e71e420fe8e8a3b62266ef066ae6d890965/Modules/IO/ImageBase/include/itkImageIOBase.h#L105) I'd expected that the code should be backwards compatibly, unless `ITK_LEGACY_REMOVE` is defined. It's possible that the `brew` version was configured that way of course (although that would be quite naughty).

In any case, it seems we need to check ITK version and have preprocessor stuff to use the new behaviour from 5.1 onwards.

**Comment by KrisThielemans** [comment]
Looks like we should use `ITK_VERSION_MAJOR` and `ITK_VERSION_MINOR`
https://github.com/InsightSoftwareConsortium/ITK/blob/c2b399eef1248465a848a26231de66a8c9715132/Modules/Core/Common/src/itkConfigure.h.in#L164-L166

and probably `itk::ImageIOBase::IOPixelEnum::VECTOR`
