### PR TITLE
Projdata visualisation PyQt5 fix for older python and PyQt5 versions

### LINKED ISSUE #1170: ProjDataVisualisation not working with Python 3.6.9 and PyQt5 v5.10.1
A slightly specific use case but there we go. I get two types of errors. 

One relates to the type hints leading to a `TypeError`:
```
  File "/home/robert/devel/stir/PrescientSTIR/STIR/examples/python/projdata_visualisation/BackendTools/STIRInterface.py", line 105, in ProjDataVisualisationBackend
    def get_limits(self, dimension: ProjDataDims, segment_number: int) -> tuple[int, int]:
TypeError: 'type' object is not subscriptable
```
This appears to be a consequence of different python versions. I compared python 3.6.9 (Ubuntu), where this script fails, with python 3.9.13 (Macos), where the current script works.

______

The other relates to a `AttributeError`:

```
  File "/home/robert/devel/stir/PrescientSTIR/STIR/examples/python/projdata_visualisation/ProjDataVisualisation.py", line 48, in __init__
    styleComboBox.textActivated.connect(self.change_UI_style)
AttributeError: 'QComboBox' object has no attribute 'textActivated'
```
This appears to be caused by changes by PyQt5 to method names and structure.

### PR DESCRIPTION
**Pull request by Robert-PrescientImaging**
Fixes #1170

Removes the complex typehints (e.g. `tuple[int, int]`) and adds a `try`-`except`. This resolves the issue on my machine.

### CODE REVIEW

**Comment by robbietuk** [comment]
Works on my MacOS python 3.9.13 with PyQt5 v5.15.7
