### ISSUE TITLE
Compilation error on Linux system with ROOT enabled

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#678]
Installing STIR on Linux (Myriad cluster) with ROOT support. ROOT is preinstalled by the Myriad cluster and is version `6.04`. STIR installs with same configuration, but without ROOT support. 

This appears to use the methods introduced in #667.  In the ccmake, the ROOT paths are given to be 

```
 CERN_ROOT_CONFIG                */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/bin/root-config                                                              
 CERN_ROOT_Core_LIBRARY          */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libCore.so                                                          
 CERN_ROOT_Gpad_LIBRARY          */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libGpad.so                                                          
 CERN_ROOT_Graf3d_LIBRARY        */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libGraf3d.so                                                        
 CERN_ROOT_Graf_LIBRARY          */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libGraf.so                                                          
 CERN_ROOT_Hist_LIBRARY          */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libHist.so                                                          
 CERN_ROOT_MathCore_LIBRARY      */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libMathCore.so                                                      
 CERN_ROOT_Matrix_LIBRARY        */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libMatrix.so                                                        
 CERN_ROOT_MultiProc_LIBRARY     *CERN_ROOT_MultiProc_LIBRARY-NOTFOUND                                                                                 
 CERN_ROOT_Net_LIBRARY           */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libNet.so                                                           
 CERN_ROOT_Physics_LIBRARY       */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libPhysics.so                                                       
 CERN_ROOT_Postscript_LIBRARY    */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libPostscript.so                                                    
 CERN_ROOT_RIO_LIBRARY           */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libRIO.so                                                           
 CERN_ROOT_Rint_LIBRARY          */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libRint.so                                                          
 CERN_ROOT_Thread_LIBRARY        */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libThread.so                                                        
 CERN_ROOT_Tree_LIBRARY          */shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libTree.so  
```

STIR generates and configures without error. When `make`, I get the following error:

```
[  8%] Building CXX object src/spatial_transformation_buildblock/CMakeFiles/spatial_transformation_buildblock.dir/InvertAxis.cxx.o
/home/rmaprrt/bin/STIR_bin/STIR/src/spatial_transformation_buildblock/InvertAxis.cxx: In member function ‘int stir::InvertAxis::invert_axis_index(int, int, const string&)’:
/home/rmaprrt/bin/STIR_bin/STIR/src/spatial_transformation_buildblock/InvertAxis.cxx:90:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
[  8%] Linking CXX static library libspatial_transformation_buildblock.a
[  8%] Built target spatial_transformation_buildblock
src/IO/CMakeFiles/IO.dir/flags.make:10: *** missing separator.  Stop.
make[1]: *** [src/IO/CMakeFiles/IO.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by robbietuk** [comment]
Appears to be a conflict with something else... Disabling all over options (ITK, HDF5 etc) allows for compilation.

**Comment by KrisThielemans** [comment]
it's a remnant of having the "old" ROOT CMake conflicting with the new one I believe. Just get rid of the build and start again. did work for me.

**Comment by robbietuk** [comment]
ITK (version 4.13) appears to be conflicting with ROOT. STIR compiles with neither, ITK only, or ROOT only support. 

> it's a remnant of having the "old" ROOT CMake conflicting with the new one I believe. Just get rid of the build and start again. did work for me.

Unfortunately this is a new build directory. I just rebuilt from scratch to confirm.

**Comment by robbietuk** [comment]
In a correct compliation (without ROOT support), I get the following message here:
```
[ 10%] Linking CXX static library libspatial_transformation_buildblock.a
[ 10%] Built target spatial_transformation_buildblock
[ 10%] Linking CXX static library libIO.a
[ 10%] Built target IO
```

**Comment by KrisThielemans** [comment]
ok. can you attach the CMakeCache.txt and src/IO/CMakeFiles/IO.dir/flags.make? I had a spurious line-break in the flags, which (now that I remember) seemed to have to do with using the output of `root_config` to set the include directory. It is possible it doesn't generate a conflict without ITK as it happens that there are no extra flags after it then.

When avoiding to use `root_config`, (but setting `ROOT_DIR`) everything was fine.

anyway, post the files please.

**Comment by robbietuk** [comment]
CMakeCache.txt
[CMakeCache.txt](https://github.com/UCL/STIR/files/5188186/CMakeCache.txt)

src/IO/CMakeFiles/IO.dir/flags.make (.txt for github)
[flags.make.txt](https://github.com/UCL/STIR/files/5188189/flags.make.txt)

**Comment by KrisThielemans** [comment]
yep. the flags.make sets `CXX_INCLUDES` with a newline, but it shouldn't.

As `CERN_ROOT_CONFIG` is set, you are using the "old" style (which possibly used to work), as opposed to the new style CMake Config (by setting `ROOT_DIR`). It's a bit disappointing that it falls-back to the old version of course. Can you give some info on your set-up? 
- Did you `source thisroot.sh`? 
- Is `root_config` in your path? 
- Is `ROOTSYS` set? 
- Does `cmake/ROOTConfig.cmake` exist in your root install?

I think we need 2 fixes:
- I believe the problem will go away when adding `OUTPUT_STRIP_TRAILING_WHITESPACE` to
https://github.com/UCL/STIR/blob/40d70e5c9ea7e8efc95b3999422756858c27f084/src/cmake/FindCERN_ROOT.cmake#L56-L57
- we need to let `FindCERN_ROOT.cmake` have a higher chance of finding `ROOTConfig.cmake` as that's the way forward. For that I need the info above.

**Comment by robbietuk** [comment]
> Did you source thisroot.sh?

I believe it does something analogous. This is hard as it is installed and paths are handled by UCL myriad's module system.
```
setenv		 ROOTSYS /shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2 
prepend-path	 PATH /shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/bin 
prepend-path	 MANPATH /shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/share/man 
prepend-path	 LD_LIBRARY_PATH /shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root 
```
> Is root_config in your path?

Yes, it exists in `/shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/bin `
> Is ROOTSYS set?

Yes.

> Does cmake/ROOTConfig.cmake exist in your root install?

No. Again because this is setup by Myriad this does not seem to exist. I used grep to look.

Therefore, should this be defaulting to the old method if `cmake/ROOTConfig.cmake` does not exist?

**Comment by KrisThielemans** [comment]
@robbietuk did you try `OUTPUT_STRIP_TRAILING_WHITESPACE`?

**Comment by robbietuk** [comment]
> @robbietuk did you try `OUTPUT_STRIP_TRAILING_WHITESPACE`?

Yes, the modification allows for compilation on the Linux system with the issue. Shall I make a pull request with the change or would you like to just push to master as it is so small?
